armor:
    legendary diamond:
        material: Bedrock
        color: black
        durability: &kd-4000
        lore: Yeeehaaa!
        
    quartz:
        material: Quartz
        color: white
        durability: &kd-2500
        lore:
        PROTECTION_ENVIRONMENTAL: 10
        PROTECTION_PROJECTILE: 0
        PROTECTION_EXPLOSIONS: 0
        PROTECTION_FIRE: 0
        THORNS: 0
        head:
            durability: &kd-2500
            lore:
            enchantments:
                PROTECTION_ENVIRONMENTAL: 10
                PROTECTION_PROJECTILE: 0
                PROTECTION_EXPLOSIONS: 0
                PROTECTION_FIRE: 0
                THORNS: 0
        chest:
            durability: &kd-2500
            lore:
            enchantments:
                PROTECTION_ENVIRONMENTAL: 10
                PROTECTION_PROJECTILE: 0
                PROTECTION_EXPLOSIONS: 0
                PROTECTION_FIRE: 0
                THORNS: 0
        leggings:
            durability: &kd-2500
            lore:
            enchantments:
                PROTECTION_ENVIRONMENTAL: 10
                PROTECTION_PROJECTILE: 0
                PROTECTION_EXPLOSIONS: 0
                PROTECTION_FIRE: 0
                THORNS: 0
        boots:
            durability: &kd-2500
            lore:
            enchantments:
                PROTECTION_ENVIRONMENTAL: 10
                PROTECTION_PROJECTILE: 0
                PROTECTION_EXPLOSIONS: 0
                PROTECTION_FIRE: 0
                THORNS: 0
            
            
            
    emerald:
        material: Emerald
        color: RichLime
        head:
            durability: &kd-2000
            enchantments:
                PROTECTION_ENVIRONMENTAL: 10
                PROTECTION_PROJECTILE: 0
                PROTECTION_EXPLOSIONS: 0
                PROTECTION_FIRE: 0
                THORNS: 0
            lore:
        chest:
            durability: &kd-2000
            enchantments:
                PROTECTION_ENVIRONMENTAL: 10
                DURABILITY : 10
                PROTECTION_PROJECTILE: 0
                PROTECTION_EXPLOSIONS: 0
                PROTECTION_FIRE: 0
                THORNS: 0
            lore:
        leggings:
            durability: &kd-2000
            enchantments:
                PROTECTION_ENVIRONMENTAL: 10
                DURABILITY : 10
                PROTECTION_PROJECTILE: 0
                PROTECTION_EXPLOSIONS: 0
                PROTECTION_FIRE: 0
                THORNS: 0
            lore:
        boots:
            durability: &kd-2000
            enchantments:
                PROTECTION_ENVIRONMENTAL: 10
                DURABILITY : 10
                PROTECTION_PROJECTILE: 0
                PROTECTION_EXPLOSIONS: 0
                PROTECTION_FIRE: 0
                THORNS: 0
            lore:
                
tools:
    quartz:
        material: Quartz
        durability: &kd-2500
        lore:
        PROTECTION_ENVIRONMENTAL: 10
        PROTECTION_PROJECTILE: 0
        PROTECTION_EXPLOSIONS: 0
        PROTECTION_FIRE: 0
        THORNS: 0
